# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvest',
            name='rest',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
