# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_kvest_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvest',
            name='rest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kvest',
            name='state',
            field=models.IntegerField(),
        ),
    ]
