# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0003_auto_20181014_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kvest',
            old_name='rest',
            new_name='need_reset',
        ),
        migrations.RenameField(
            model_name='kvest',
            old_name='state',
            new_name='status',
        ),
    ]
