# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0004_auto_20181015_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zagadka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_reset', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='kvest',
            name='need_reset',
        ),
        migrations.AddField(
            model_name='kvest',
            name='zagadka1',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='Server.Zagadka'),
            preserve_default=False,
        ),
    ]
