# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0005_auto_20181020_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='zagadka',
            name='name',
            field=models.CharField(default='Zagadka', max_length=50),
        ),
    ]
