# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0006_zagadka_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zagadka',
            old_name='need_reset',
            new_name='status',
        ),
    ]
