# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0007_auto_20181020_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvest',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
