# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0008_auto_20181020_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvest',
            name='zagadka1',
        ),
    ]
