# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0009_remove_kvest_zagadka1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zagadka',
        ),
        migrations.RemoveField(
            model_name='kvest',
            name='status',
        ),
        migrations.AddField(
            model_name='kvest',
            name='status_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvest',
            name='status_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvest',
            name='status_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvest',
            name='status_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvest',
            name='status_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvest',
            name='status_6',
            field=models.IntegerField(default=0),
        ),
    ]
